import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="flex flex-col h-screen max-h-full bg-white">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          rel="preload"
          as="style"
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700&display=swap"
        />
        <noscript>
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700&display=swap"
          />
        </noscript>
      </Head>

      <header className="p-2 text-white bg-indigo-700">
        <span className="text-2xl">Bureau</span>
        <span className="ml-1 text-xs italic font-thin">
          A Smart ERP for Small Business
        </span>
      </header>
      <main className="p-1 bg-indigo-700 text-md grow">
        <div className="h-full p-1 bg-white rounded-lg">CONTENT</div>
      </main>

      <footer className="p-1 text-xs text-white bg-indigo-700">
        <a href="#" target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
